### ISSUE TITLE
Error with 'cloning_reference_wav'

### ISSUE THREAD

**Issue by ajeema** [KoljaB/LocalAIVoiceChat#6]
All libraries seem to have been installed properly. However I get this error when trying to run

`C:\Users\USER\code\LocalAIVoiceChat-main>start.bat
cuda not available
llama_cpp_lib: return llama_cpp
Initializing LLM llama.cpp model ...
llama.cpp model initialized
Initializing TTS CoquiEngine ...
Traceback (most recent call last):
  File "C:\Users\USER\code\LocalAIVoiceChat-main\ai_voicetalk_local.py", line 111, in <module>
    coqui_engine = CoquiEngine(cloning_reference_wav="female.wav", language="en", speed=1.0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python311\site-packages\RealtimeTTS\engines\base_engine.py", line 11, in __call__
    instance = super().__call__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CoquiEngine.__init__() got an unexpected keyword argument 'cloning_reference_wav'`

Please advise

**Comment by ajeema** [comment]
Removing it seems to have worked.

**Comment by KoljaB** [comment]
Probably update to latest [RealtimeTTS](https://github.com/KoljaB/RealtimeTTS/releases/tag/v0.3.40) version. Parameter cloning_reference_wav ist now named voice.

**Comment by vlasov01** [comment]
I've changed line 109 from CoquiEngine(cloning_reference_wav="female.wav", language="en", speed=1.0) to coqui_engine = CoquiEngine(voice="female.wav", language="en", speed=1.0) and it is working now for me.
